version: 2

before:
  hooks:
    - go mod tidy
builds:
  - binary: markscribe
    flags:
      - -trimpath
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  - formats:
      - tar.gz
      - zip

nfpms:
  - id: markscribe
    builds:
      - markscribe
    vendor: buluma
    homepage: "https://fribbledom.com/"
    maintainer: "Christian Muehlhaeuser <buluma@gmail.com>"
    description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

brews:
  - repository:
      owner: buluma
      name: homebrew-tap
    commit_author:
      name: "Christian Muehlhaeuser"
      email: "buluma@gmail.com"
    homepage: "https://fribbledom.com/"
    description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
    # skip_upload: true

checksum:
  name_template: "checksums.txt"
snapshot:
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
