version: 2

before:
  hooks:
    - go mod tidy
builds:
  - binary: markscribe
    flags:
      - -trimpath
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: markscribe
    vendor: buluma
    homepage: "https://fribbledom.com/"
    maintainer: "Michael Buluma <bulumaknight@gmail.com>"
    description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

homebrew_taps:
  - repository:
      owner: buluma
      name: homebrew-tap
    commit_author:
      name: "Michael Buluma"
      email: "bulumaknight@gmail.com"
    homepage: "https://fribbledom.com/"
    description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"

checksum:
  name_template: "checksums.txt"
snapshot:
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
